arb-dir: l10n
template-arb-file: app_es.arb
output-class: AppLocalizations
output-dir: lib/localizations
output-localization-file: app_localizations.dart
untranslated-messages-file: l10n/untranslated.txt
synthetic-package: false
